# 自定义配置
app:
  crypto:
    # 是否启用加密
    status: true
    # 密钥文件位置
    rsa-public-key: classpath:crypto/public.key
    rsa-private-key: classpath:crypto/private.key
    des-first-key: classpath:crypto/des1.key
    des-second-key: classpath:crypto/des2.key
    des-third-key: classpath:crypto/des3.key
    aes-key: classpath:crypto/aes.key
    aes-iv-key: classpath:crypto/aes-iv.key

# spring的配置
spring:
  # 配置数据源
  datasource:
    # 基本数据库信息
    url: jdbc:mysql://x.x.x.x/xxx?useUnicode=true&characterEncoding=utf-8
    # xxx
    username: xxx
    # xxx
    password: xxx